<img src="images/smiley/angel_smile.png" class="angel_smile">
<img src="images/smiley/angry_smile.png" class="angry_smile">
<img src="images/smiley/broken_heart.png" class="broken_heart">
<img src="images/smiley/confused_smile.png" class="confused_smile">
<img src="images/smiley/cry_smile.png" class="cry_smile">
<img src="images/smiley/devil_smile.png" class="devil_smile">
<img src="images/smiley/embarrassed_smile.png" class="embarrassed_smile">
<img src="images/smiley/envelope.png" class="envelope">
<img src="images/smiley/heart.png" class="heart">
<img src="images/smiley/kiss.png" class="kiss">
<img src="images/smiley/lightbulb.png" class="lightbulb">
<img src="images/smiley/omg_smile.png" class="omg_smile">
<img src="images/smiley/regular_smile.png" class="regular_smile">
<img src="images/smiley/sad_smile.png" class="sad_smile">
<img src="images/smiley/shades_smile.png" class="shades_smile">
<img src="images/smiley/teeth_smile.png" class="teeth_smile">
<img src="images/smiley/thumbs_down.png" class="thumbs_down">
<img src="images/smiley/thumbs_up.png" class="thumbs_up">
<img src="images/smiley/tongue_smile.png" class="tongue_smile">
<img src="images/smiley/whatchutalkingabout_smile.png" class="whatchutalkingabout_smile">
<img src="images/smiley/wink_smile.png" class="wink_smile">